language: node_js
node_js: 8
script:
- npm run build
- npm run test
deploy:
  provider: npm
  email: bryphe@outlook.com
  api_key:
    secure: o6HLRqYWAdSWGrmN9DaWCM7D1EUzJ28kqnTSLdzm2KdQpBw2ggFQVxtm0f7oGKWyH727vfC4dZkICj8bwSfnKlb6h2sdAYJjL3ICeqQDHb/1pSEiWi61sZ2vG8QQQHAfFramk+87jSaaKwgwMKsGom09UIi36jqlv4nKtt6/GPa/mcA/hRUAfo2Gjas0eTHIAzndptFRvUglVaw4tJgbQuipUD84Rrza4YK+toBXpweMWGSdoWWZaGp2RVAb+o0hhpvEi9L4yJsBn2pQHwSF28t4l0NkxecmFjRavo7MCNPjGSFoEKsfHKD7b91BZHMzrrm2u+bQrXUOaCnsETM6zGpyJ7L/P3EvqmK6mYn9Vy23K+8Fn+7zUIhFoPaHgIptPQLD4cCmdrkHXCHPQsk96IB9wZwaA7B1atgsZMj3oNdLjZsCOaygo2fWKlxvSZh78Llz1VXwmfa79rrPeQ1A+VIdlfsmZ0A99BY7uJnHvwtZK1hvbd4w8TXqkvn7ycg6Lg2LB5uxnDusTopbWL+qBTRDUNx+6xw54yj3IzxNZjy0fx1CXS73fVjdKmri4919IbEUsfyRi/dZdmcNAoeGww8XosQiL0BsUBSYvEy1HYuANmX8n+JiBdGcqOq2SiwSA/Lk8EUuBf6b3pkSJxsACbtZH3p+aasavkb6JZpqKo4=
  on:
    tags: true
    repo: onivim/vscode-snippet-parser
